language: python
python:
  - 2.7

env:
  global:
  - secure: |-
      ZBDnPcgNo86ve0O71/QSGyq/A2/jk/yfcoEWC5BOSKfG8L1lxrnenqOY34Cx
      Blm8d0iiX1fut444dTms8g2DEogYn95kK4OqW+0n8qdqQax22LxO4849oevq
      CjPao9pR4yWPrRZg/+cCNQelUYfQZKtYzXVKMKFlhs/0FfCITLQ=  # COVERALLS_REPO_TOKEN

install:
  - python bootstrap.py
  - bin/buildout

script:
  - bin/coverage run --source=tests.py --branch bin/nosetests
  - bin/coverage html -i
  - bin/mrbob -O plone.foo --config test_answers.ini ./bobtemplates/plone
  - cd plone.foo
  - make
  - cd ..
  - bin/mrbob -O foo --config test_answers.ini ./bobtemplates/pyramid
  - cd foo
  - make

after_success:
 - pip install python-coveralls==2.4.0
 - coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#niteoweb"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
