language: python
python:
  - 2.7

install:
  - python setup.py develop
  - easy_install mr.bob[test,development]

script:
  - mrbob -O collective.foo --config .travis_answers.ini ./bobtemplates/plone
  - cd collective.foo
  - make

notifications:
  irc:
    - "irc.freenode.org#niteoweb"
  email:
    - maintenance@niteoweb.com
