language: python
python:
  - 2.7

install:
  - python bootstrap.py
  - bin/buildout

script:
  - bin/nosetests
  - bin/mrbob -O plone.foo --config test_answers.ini ./bobtemplates/plone
  - cd plone.foo
  - make
  - cd ..
  - bin/mrbob -O foo --config test_answers.ini ./bobtemplates/pyramid
  - cd foo
  - make

notifications:
  irc:
    - "irc.freenode.org#niteoweb"
