language: python
python:
  - 2.7

env:
  global:
  - secure: |-
      Gs5x8Wh6wIn6fdhQYTU+gro+EkISSbegB6ECPHsgekEIUyTPtXZ4QK1FqHE3
      ZFV+BfmK+Hop+nksWki2l1Tw1zYvVgoa5bqk6Lrj+MlnwnuR7oRCU3FCu9cX
      ZsQpCYVKoEaklxzcvN/7Gu3cx3DuZgg96191akK82/NhODUwQkI=  # COVERALLS TOKEN

install:
  - python bootstrap.py
  - bin/buildout

script:
  - bin/coverage run --source=tests.py --branch bin/nosetests
  - bin/coverage html -i
  - bin/mrbob -O plone.foo --config test_answers.ini ./bobtemplates/plone
  - cd plone.foo
  - make
  - cd ..
  - bin/mrbob -O foo --config test_answers.ini ./bobtemplates/pyramid
  - cd foo
  - make

after_success:
 - pip install python-coveralls==2.4.0
 - coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#niteoweb"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
